---
apiVersion: v1
kind: Secret
metadata:
  name: caddy-secret
  labels:
    app: caddy-secret
    environment: production
data:
  .dockerconfigjson: <BASE64_ENCODED_DOCKER_CONFIG_JSON>
type: kubernetes.io/dockerconfigjson
